# Generated by Django 5.0.6 on 2025-11-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="base_unit",
            field=models.CharField(
                choices=[
                    ("m", "Метры"),
                    ("pcs", "Штуки"),
                    ("sheet", "Листы"),
                    ("sqm", "Кв. метры"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="default_unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="package_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Сколько базовых единиц в упаковке (например, 50 м в рулоне)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="package_unit_label",
            field=models.CharField(
                blank=True,
                help_text="Название упаковки: рулон, пачка, коробка…",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity_on_hand",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
