# Generated by Django 5.0.6 on 2025-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_inventoryitem_base_unit_inventoryitem_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("development", "В разработке"),
                    ("office", "В офисе"),
                    ("workshop", "В цеху"),
                    ("installation", "Монтаж"),
                    ("done", "Завершено"),
                ],
                default="development",
                max_length=32,
            ),
        ),
    ]
