# Generated by Django 5.0.6 on 2025-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_expense_client_address_order_is_locked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="due_date",
            new_name="end_date",
        ),
        migrations.AddField(
            model_name="order",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="order",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата завершения"),
        ),
    ]
