# Generated by Django 5.0.6 on 2025-11-26 14:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_remove_order_due_date_order_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage_date",
                    models.DateField(default=datetime.date.today, verbose_name="Дата"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="portal.inventoryitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_usages",
                        to="portal.order",
                        verbose_name="Проект / заказ",
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_date", "-created_at"],
            },
        ),
    ]
