# Generated by Django 5.0.6 on 2025-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_defectrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="defectrecord",
            name="status",
            field=models.CharField(
                choices=[("closed", "Закрыто"), ("completed", "Завершено")],
                default="closed",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
